baseURL = 'https://bycamino.com/'
languageCode = 'en-us'
title = 'Camino'
contributors = [ "ben" ]
[taxonomies]
  contributor = 'contributors'
  service = 'services'
[params.taxonomies.services]
  "Product Design" = "service-product"
  "Branding" = "service-branding"
  "Web Development" = "service-web"