baseURL = 'https://bycamino.netlify.app/'
languageCode = 'en-us'
title = 'Camino'
contributors = [ "ben" ]
[taxonomies]
  contributor = 'contributors'
  service = 'services'
  client = 'clients'
[params.taxonomies.services]
  "UX Design" = "service-ux-design"
  "Web Development" = "service-web-development"
  "Messaging" = "service-messaging"
[pagination]
  pagerSize = 8