baseURL = 'https://ben-camino.github.io/bycamino/'
languageCode = 'en-us'
title = 'Camino'
[taxonomies]
  contributor = 'contributors'
  service = 'services'
  client = 'clients'
[caches]
  [caches.images]
    dir = ':cacheDir/images'